config/routes.rb
Rails.application.routes.draw do
  root 'fruits#index'
  resources :customers, except: [:show, :index, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :fruits, product: 'Fruit', only: :index do
    resources :checkouts,  only: [:new, :create, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :customer

  validates :token, :last_4, presence: true
  validates :token, uniqueness: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  before_validation :generate_token
  has_secure_password
  has_many :cards
  validates :email, presence: true
  validates :email, uniqueness: true
  validate :valid_bt_customer

  def generate_token
    self.bt_id = SecureRandom.hex
  end

  def valid_bt_customer
    result = Braintree::Customer.create(
      :id => self.bt_id,
      :first_name => self.username
    )
    unless result.success?
      self.errors.add(:bt_id, :blank, message: "Token is required")
    end
  end
end

app/models/fruit.rb
class Fruit < ApplicationRecord
  def product_path
    ['/fruits',self.id].join('/')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  include CheckoutsHelper, SessionsHelper

  TRANSACTION_SUCCESS_STATUSES = [
    Braintree::Transaction::Status::Authorizing,
    Braintree::Transaction::Status::Authorized,
    Braintree::Transaction::Status::Settled,
    Braintree::Transaction::Status::SettlementConfirmed,
    Braintree::Transaction::Status::SettlementPending,
    Braintree::Transaction::Status::Settling,
    Braintree::Transaction::Status::SubmittedForSettlement,
  ]

  def new
    customer = current_customer
    if !!customer.cards
      @card = customer.cards.last
    end
    @fields = CheckoutsHelper.bt_form_fields
    @product = _get_purchase_product
    @client_token = Braintree::ClientToken.generate
  end

  def show
    @product = _get_purchase_product
    @transaction = Braintree::Transaction.find(params[:id])
    @result = _create_result_hash(@transaction)
  end

  def create
    customer = current_customer
    checkout = params[:checkout]
    product = _get_purchase_product
    amount = checkout[:amount].to_i
    nonce = params[:payment_method_nonce]
    save = checkout[:save] === 'on'
    purchase_amount = '%.2f' % (amount * product.price_per_lb)

    result = Braintree::Transaction.sale(
      amount: purchase_amount,
      payment_method_nonce: nonce,
      :customer_id => customer.bt_id,
      :options => {
        :submit_for_settlement => true,
        :store_in_vault_on_success => save
      }
    )
    if save && ( result.success? || result.transaction )
      card = result.transaction.credit_card_details
      customer.cards.new({token: card.token, last_4: card.last_4})
      if customer.save
        flash[:error] = 'Save unsuccessful.'
      else
        flash[:notice] = 'Card save successful.'
      end
    end 
    _checkout_redirect(result, product)
  end

  def _checkout_redirect(result, product)
    if result.success? || result.transaction
      case product.model_name.name
      when 'Fruit'
        redirect_to fruit_checkout_path(product.id, result.transaction.id)
      else
        flash[:error] = 'Something went wrong, please contact us.'
        redirect_to root_path
      end
    else
      error_messages = result.errors.map { |error| "Error: #{error.code}: #{error.message}" }
      flash[:error] = error_messages

      case product.model_name.name
      when 'Fruit'
        redirect_to new_fruit_checkout_path(product.id)
      else
        redirect_to root_path
      end
    end
  end
  def _create_result_hash(transaction)
    t = transaction.credit_card_details
    status = transaction.status
    reciept = [
      "TransactionID: #{transaction.id}",
      "Date: #{transaction.created_at}",
      "Amount: $#{show_amount_cents(transaction.amount)}"
    ]
      
    if t.card_type != nil
      reciept.push("Payment Method: #{t.card_type} ending in #{t.last_4}")
    end
    
    if TRANSACTION_SUCCESS_STATUSES.include? status
      result_hash = {
        :header => "Sweet Success!",
        :icon => "success_grape",
        :message => "Thanks a bunch! Everything went GRAPE!",
        :reciept => reciept
      }
    else
      result_hash = {
        :header => "Transaction Failed",
        :icon => "fail_pear",
        :message => "It ap-PEAR-s something went wrong"
      }
    end
  end
  
  def _get_purchase_product
    model = params["product"].constantize
    product_key = params["product"].foreign_key
    model.find_by(id: params[product_key])
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  include CheckoutsHelper, SessionsHelper
  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      flash[:notice] = 'Account creation successful!'
      log_in(@customer)
      redirect_to checkout_cart
    else
      flash[:alert] = 'Account creation failed'
      redirect_to new_customer_path
    end
  end
  
  private
  def customer_params
      params.require(:customer).permit(:username, :email, :password)
  end
end

app/controllers/fruits_controller.rb
class FruitsController < ApplicationController

  def index
    @fruits = Fruit.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper, CheckoutsHelper
  def new
    add_to_cart(params[:type],params[:item_id])
    @customer = Customer.new
  end

  def create
    @customer = Customer.find_by(email: customer_params[:email])
    if @customer && @customer.authenticate(customer_params[:password])
      log_in(@customer)
      flash[:notice] = "Login Successful!"
      redirect_to checkout_cart
    else
      flash[:alert] = "Login failed"
      redirect_to new_session_path
    end
  end

  def destroy
    flash[:notice] = "Thanks for stopping by!"
    log_out
    redirect_to root_path
  end

  private
  def customer_params
      params.require(:session).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
  def checkout_cart
    cart = session[:cart]
    cart_path = "/#{session[:cart]["type"]}/#{session[:cart]["item_id"]}/checkouts/new"
  end
  
  def show_amount_cents(cost)
    str_cost = cost.to_s
    if !!(/^\d*$/ =~ str_cost) #nil on no cents
      str_cost = [str_cost, '00'].join('.')
    elsif !!(/\.[0-9]$/ =~ str_cost) #nil on only tenths
      str_cost = [str_cost, '0'].join('')
    else
      str_cost
    end
  end

  def self.bt_form_fields(options={})
    if options.fetch(:hostedFields, false)
      braintree_options = {}
      CHECKOUT_FIELDS.each do |f|
        braintree_options.store(
          f.fetch(:type, f[:name]), {
            selector: ['#',f[:name]].join('')
          }
        )
      end
      braintree_options.to_json.html_safe
    else
      CHECKOUT_FIELDS
    end
  end

  protected
  CHECKOUT_FIELDS = [{
      type: 'number',
      name: 'card-number',
      display: 'Card Number'
    }, {
      type: 'expirationDate',
      name: 'expiration-date',
      display: 'Exp. date'
    }, {
      name: 'cvv',
      display: 'CVV'
    }, {
      type: 'postalCode',
      name: 'zip',
      display: 'Billing Zipcode'
  }]
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/fruits_helper.rb
module FruitsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def logged_in
    session[:customer_id] != nil
  end

  def log_in(customer)
    session[:customer_id] = customer.id
  end

  def current_customer
   @current_customer ||= Customer.find_by(id: session[:customer_id])
  end

  def log_out
    session[:customer_id] = nil
    session[:cart] = nil
  end

  def add_to_cart(type, id)
    session[:cart] = {type: type, item_id: id}
  end
end

app/views/checkouts/_form.html.erb
<div id='payment-section' class='container-fluid'>
  <div class="row">
    <div class="col-md-6 form">
      <label class="ammount-label" for="amount">
        <span class="ammount-field-name">Amount(lbs)</span>
        <div class="input-wrapper amount-wrapper">
          <input
            id="amount"
            class="ammount-field"
            name="amount"
            type="tel"
            min="1"
            value="1"
          >
        </div>
      </label>
    </div>
    <div class="col-md-2">
      <button class='update-btn btn btn-default'> = </button>
    </div>
    <div class="col-md-3 form">
        <label class="ammount-label" >
          <span class="ammount-field-name">Total cost(USD)</span>
          <div class="total-wrapper">
            <span class="total-cost total-field" id="total"><%= product.price_per_lb  %></span>
          </div>
        </label>
      </div> 
    </div>
  </div>
  <%= render partial: 'notification' %>
  <%= form_tag(fruit_checkouts_path, id: "braintree-payment-form") do %>
    <section class='paypal-section-wrap'>
      <input
        id='checkout-amount'
        type='hidden'
        name='checkout[amount]'
        value='1'
      >
      <div class="row form form-align">
        <div class="column">  
          <div
            id="paypal-container"
            class="centered-btn"
          >
          </div>
        </div>
      </div>
      <div id='cc-inputs'>
      <% fields.each do |f| %>
        <div class="row form form-align">
          <div class="column">
            <label
              class="<%=f[:name]%>-label form-label"
              for="<%=f[:name]%>"
            >
              <span class="field-name">
                <%=f[:display]%>
              </span>
              <div
                class="input-wrapper <%=f[:name]%>-wrapper">
                <div
                  id="<%=f[:name]%>"
                  class="BT-input"
                  name="checkout[<%=f[:name]%>]"
                >
                </div>
              </div>
            </label>
          </div>
        </div>
      <% end %>
    </div>
    </section>
    <div class='row'>
      <div class='col-sm-6 col-sm-offset-2'>
      <label class="form-label" for="save-card-option">Save this card?
        <input id="save-card-option" type="checkbox" name="checkout[save]">
        <button
          id='BT-btn'
          class="btn btn-block btn-info"
          type="submit"
        >
          <span>Submit</span>
        </button>
      </label>
      <div>
    </div>
  <% end %>
  <script type="text/javascript">
    checkoutsWillEnter({
      client_token: "<%=@client_token %>",
      btOptions: <%= CheckoutsHelper.bt_form_fields({
        'hostedFields': true
      })%>
    })
  </script>
</div>

app/views/checkouts/_notification.html.erb
<div id="notice-wrapper">
  <% if flash[:error] %>
    <div class="show notice error notice-error">
      <span class="notice-message">
        <%= alert_string(flash[:error]) %>
      </span>
    </div>
  <% end %>
</div>

app/views/checkouts/new.html.erb
<% if logged_in  %>
  <div class="row header-row">
    <div class="col-md-3">
        <h1 class='main-title'><%= @product.name.capitalize  %></h1>
    </div>
    <div class="home-link col-md-3 col-md-offset-6">
      <%=link_to 'Home', root_path, class: 'main-title'  %> | <%= link_to 'Logout', session_path(1), method: :delete, class: 'main-title' %>
    </div>
  </div>
  <div class="row checkout-content">
    <div class="col-md-5 fruit-card">
      <div class="product-details-wrapper" >
        <%= image_tag(@product.display_url, class: 'show-img') %>
        <div class="description-wrapper">
          <p><%= @product.description  %></p>
        </div>
      </div>
    </div>
    <div class="col-md-6 purchase-form-wrapper">
          <%= render(:partial => 'form', :locals => { :product => @product, :fields => @fields }) %>
    </div>
  <div>
<% end %>

app/views/checkouts/show.html.erb
<div class="row">
  <div class="col-md-3">
      <h1 class='main-title'>Fruit Store</h1>
  </div>
  <div class="home-link col-md-3 col-md-offset-6">
    <%=link_to 'Home', root_path, class: 'main-title'  %>
  </div>
</div>
<div class="result-wrapper">
  <div class="response container">
    <div class="content">
      <% if @result %>
        <div class="icon">
          <img src=<%= asset_path("#{@result[:icon]}.png") %> alt="">
        </div>

        <h1><%= @result[:header] %></h1>
        <section>
          <p><%= @result[:message] %></p>
        </section>
      <% else %>
        <section>
          <p>Test another transaction or see the Braintree API response.</p>
      </section>

      <% end %>
    </div>
  </div>
  <%if @result[:reciept] %>
    <div class="reciept">
      <h3>Reciept</h3>
      <%@result[:reciept].each do |line| %>
        <p><%= line  %></p>
      <% end %>
    </div>
  <% end %>
  <br><br>
  <section>
    <a class="button primary back" href="<%=@product.product_path%>/checkouts/new">
      <span>Test Another Transaction</span>
    </a>
  </section>
</div>

app/views/customers/_form.html.erb
<div class="row form form-align">
  <div class="column">
    <label
      class="email-label form-label"
      for="email"
    >
      <span class="field-name">
        email
      </span>
      <div
        class="input-wrapper email-wrapper">
        <input
          type="email"
          id="email-field"
          class="BT-input"
          name="<%=form_name %>[email]"
        >
      </div>
    </label>
  </div>
</div>
<div class="row form form-align">
  <div class="column">
    <label
      class="password-label form-label"
      for="password"
    >
      <span class="field-name">
        password
      </span>
      <div
        class="input-wrapper password-wrapper">
        <input
          type="password"
          id="password-field"
          class="BT-input"
          name="<%=form_name %>[password]"
        >
      </div>
    </label>
  </div>
</div>

app/views/customers/create.html.erb
<h1>Customers#create</h1>
<p>Find me in app/views/customers/create.html.erb</p>

app/views/customers/new.html.erb
<div id='new-customer-form-wrapper' class='result-wrapper'>
  <div class='container-fluid'>
    <h3 class='errors'><%= flash[:alert]  %><h3>
  <%= form_tag(customers_path, id: "new-customer-form") do %>
    <div class="row form form-align">
      <div class="column">
        <label
          class="name-label form-label"
          for="name"
        >
          <span class="field-name">
            name
          </span>
          <div
            class="input-wrapper name-wrapper">
            <input
              type="text"
              id="name-field"
              class="BT-input"
              name="customer[username]"
            >
          </div>
        </label>
      </div>
    </div>
    <%= render partial: 'form', locals: {form_name: "customer"} %>
    <div class='row'>
      <div class='col-sm-6 col-sm-offset-3'>
        <button
          id='BT-btn'
          class="btn btn-block btn-info"
          type="submit"
        >
          <span>Register</span>
        </button>
      <div>
    </div>
  <% end %>
  </div>
</div>

app/views/fruits/_card.html.erb
<div class='item item-responsive'>
  <div class='top-details profile-wrapper'>
    <h3><%= fruit.name  %></h3>
    <strong>
      <p></p>
    </strong>
  </div>
  <div class='inner-wrapper'>
    <%= image_tag(fruit.display_url, class: 'card-img') %>
  </div>
  <div class='container-fluid responsive-blurb bottom-details profile-wrapper'>
    <div class='row'>
      <div class='col-sm-3 col-xs-3 main-character-icon'>
        <h3>$<%= fruit.price_per_lb  %>/lb</h3>
        <% if logged_in  %>
          <%= link_to('Purchase', new_fruit_checkout_path(fruit), class: "btn btn-sm btn-info", data: { no_turbolink: true }) %>
        <% else %>
          <%= link_to('Purchase', new_session_path(:type=>'fruits', :item_id => fruit.id), class: "btn btn-sm btn-info", data: { no_turbolink: true }) %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/fruits/index.html.erb
<p id="notice"><%= notice %></p>

<h1 id='brand-title' class='main-title'>The Fruit Store</h1>
<div class='container'>
  <% @fruits.each do |fruit| %>
    <%= render(:partial => 'card', :locals => { :fruit => fruit }) %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <title>BraintreeTechnicalChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.braintreegateway.com/js/braintree-2.31.0.min.js"></script>
  </head>
  <body>
    <%= yield %>
  </body>
</html>